language: cpp

sudo: required
dist: bionic

compiler:  
    - clang

before_script:
    - sudo apt-get install build-essential
    - sudo apt-get install cmake
    - cd test
    - mkdir build
    - cd build
    - cmake ..
    - make

script: ./runUnitTests
