name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create and enter test build directory
      run: mkdir test/build
    - name: configure
      working-directory: test/build
      run: cmake ..
    - name: build
      working-directory: test/build
      run: cmake --build .
    - name: test
      working-directory: test/build
      run: ctest
